version: "3"
services:
  node-dev:
    build: 
      context: .
      dockerfile: Node.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ~/.ssh:/home/.ssh
      - .:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npm run dev"
    environment: 
      - FIRESTORE_HOST="${FIRESTORE_HOST}"
      - FIRESTORE_PROJECT_ID="${FIRESTORE_PROJECT_ID}"
    ports:
      - "30101:30101"
    depends_on:
      - firestore

  firestore:
    build: 
      context: .
      dockerfile: Firestore.Dockerfile
    container_name: firestore
    ports: 
      - "8080:8080"

  